import React, { useState } from 'react'
import { Formik, FormikErrors } from 'formik'
import * as Yup from 'yup'
import classnames from 'classnames'
import Link from 'next/link'

const Auth2FA: React.FC = () => {
  const [smartPhone, setSmartPhone] = useState<boolean>(false)
  const [sms, setSms] = useState<boolean>(false)

  return (
    <section>
      <div className='container-fluid'>
        <div className='row'>
          <div className='col-lg-6'>
            <div className='dapp-signin-form'>
              <div className='signin-head'>
                <div className='dapp-header-logo'>
                  <img
                    src='/images/logo-big.png'
                    alt='logo'
                    className='img-fluid'
                  />
                </div>
                <h2>2FA Authentication</h2>
                <p>
                  Choose which methrod you want to <br />
                  use for 2FA code
                </p>
              </div>
              <div id='auth-block'>
                <div
                  className={classnames('dapp-2f-auth-block', {
                    'auth-active': smartPhone == true
                  })}
                  onClick={() => {
                    setSmartPhone(true)
                    setSms(false)
                  }}
                >
                  <div className='auth-select'>
                    <img
                      src='/images/auth-check.png'
                      alt='auth-check'
                      className='img-fluid'
                    />
                  </div>
                  <div className='dapp-2f-auth-block-lft'>
                    <h3>
                      Smartphone app <span>Recommended</span>
                    </h3>
                    <p>
                      2FA code will be generated by your smartphone app “Google
                      Authenticator”, available for iOS, Andriod and Windows
                      phone.
                    </p>
                  </div>
                  <div className='dapp-2f-auth-block-right'>
                    <img
                      src='/images/2f-img1.png'
                      alt='logo'
                      className='img-fluid'
                    />
                  </div>
                </div>
                <div
                  className={classnames('dapp-2f-auth-block mab-32', {
                    'auth-active': sms == true
                  })}
                  onClick={() => {
                    setSmartPhone(false)
                    setSms(true)
                  }}
                >
                  <div className='auth-select'>
                    <img
                      src='/images/auth-check.png'
                      alt='auth-check'
                      className='img-fluid'
                    />
                  </div>
                  <div className='dapp-2f-auth-block-lft'>
                    <h3>SMS/Phone Request</h3>
                    <p>
                      Sends 2FA code via SMS or Phone <br />
                      call.
                    </p>
                  </div>
                  <div className='dapp-2f-auth-block-right'>
                    <img
                      src='/images/2f-img2.png'
                      alt='logo'
                      className='img-fluid'
                    />
                  </div>
                </div>
              </div>
              <div className=''>
                <Link
                  href={
                    smartPhone
                      ? '/auth/confirm-no-auth'
                      : sms
                      ? '#'
                      : ''
                  }
                >
                  <button type='submit' className='bttn-primary'>
                    Next
                  </button>
                </Link>
              </div>
            </div>
          </div>
          <div className='col-lg-6 p-0'>
            <div className='sign-up-bg-image'>
              <div className='twitwr-img'>
                <a href='#'>
                  <img
                    src='/images/twitter.png'
                    alt='twitter'
                    className='img-fluid'
                  />
                </a>
              </div>
              <div>
                <img
                  src='/images/signup.png'
                  alt='signup'
                  className='img-fluid'
                />
              </div>
              <div className='top-corner'>
                <img
                  src='/images/img1.png'
                  alt='signup'
                  className='img-fluid'
                />
              </div>
              <div className='bottom-corner'>
                <img
                  src='/images/img2.png'
                  alt='signup'
                  className='img-fluid'
                />
              </div>

              <div className='linkedin-img'>
                <a href='#'>
                  <img
                    src='/images/linkedin.png'
                    alt='linkedin'
                    className='img-fluid'
                  />
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default Auth2FA
